# ==================== الكود الأول (message 4) ====================
full updated function with six positivity forms. Just copy and run this: python import numpy as np def sweep_positivity_forms(N=128): zeros = np.array([14.13, 21.02, 25.01, 30.42, 32.94, 37.59, 40.92, 43.33]) x = np.linspace(0.01, 15, N) dx = x[1] - x[0] lap = (np.diag(-2 np.ones(N)) + np.diag(np.ones(N-1), 1) + np.diag(np.ones(N-1), -1)) / dx 2 forms = { ‘quadratic’: lambda x, a: a / (x 2 + 1), ‘exponential’: lambda x, a: a np.exp(-x), ‘inverse’: lambda x, a: a / (x + 1), ‘log’: lambda x, a: a / (np.log(x + 1.1) + 1), ‘oscillatory’: lambda x, a: a np.exp(-0.3 x) np.cos(0.8 x), ‘fractional’: lambda x, a: a / (x 0.7 + 1) } best_error = float(‘inf’) best_form = None for name, func in forms.items(): for alpha in np.linspace(0.1, 3.0, 12): pos = func(x, alpha) H = -lap + np.diag(pos) evals = np.sort(np.real(np.linalg.eigvals(H))) error = np.mean(np.abs(evals[:len(zeros)] - zeros)) if error < best_error: best_error = error best_form = (name, alpha, error) print(fBest match: {best_form[0]} form, alpha={best_form[1]:.2f}, error={best_form[2]:.3f}) return best_form sweep_positivity_forms()

# ==================== الكود الثاني (الرسالة الطويلة) ====================
test different positivity wall forms against actual zeta zeros. python import numpy as np from scipy.special import zeta # for quick testing, use mpmath for precision later def test_positivity_form(pos_type=‘quadratic’, alpha=1.0, N=64): # Sample zeta zeros (imaginary parts) zeros = np.array([14.13, 21.02, 25.01, 30.42, 32.94, 37.59, 40.92, 43.33]) # Build simple operator grid x = np.linspace(0.01, 10, N) dx = x[1] - x[0] # Laplacian (second derivative) lap = np.diag(-2 np.ones(N)) + np.diag(np.ones(N-1),1) + np.diag(np.ones(N-1),-1) lap /= dx 2 # Positivity term - this is what we’re tuning if pos_type == ‘quadratic’: pos_wall = alpha / (x 2 + 1) elif pos_type == ‘exponential’: pos_wall = alpha np.exp(-x) elif pos_type == ‘inverse’: pos_wall = alpha / (x + 1) H = -lap + np.diag(pos_wall) evals = np.sort(np.real(np.linalg.eigvals(H))) # Compare first few eigenvalues to zeros diffs = np.abs(evals[:len(zeros)] - zeros) mean_error = np.mean(diffs) print(f{pos_type} (alpha={alpha:.2f}): mean error = {mean_error:.3f}) return mean_error Run this with different pos_type and alpha values. The form with the lowest mean error is your best positivity wall candidate.?

quick sweep loop that tests a bunch of positivity forms automatically. Just copy and paste this: python import numpy as np def test_all_forms(N=128): zeros = np.array([14.13, 21.02, 25.01, 30.42, 32.94, 37.59, 40.92, 43.33]) x = np.linspace(0.01, 15, N) dx = x[1] - x[0] lap = (np.diag(-2 np.ones(N)) + np.diag(np.ones(N-1),1) + np.diag(np.ones(N-1),-1)) / dx 2 forms = [‘quadratic’, ‘exponential’, ‘inverse’, ‘linear’] results = [] for form in forms: for alpha in np.linspace(0.1, 3.0, 15): if form == ‘quadratic’: pos = alpha / (x 2 + 1) elif form == ‘exponential’: pos = alpha np.exp(-x) elif form == ‘inverse’: pos = alpha / (x + 1) elif form == ‘linear’: pos = alpha / (x + 0.1) H = -lap + np.diag(pos) evals = np.sort(np.real(np.linalg.eigvals(H))) error = np.mean(np.abs(evals[:len(zeros)] - zeros)) results.append((form, alpha, error)) best = min(results, key=lambda x: x[2]) print(fBest match: {best[0]} form, alpha={best[1]:.2f}, error={best[2]:.3f}) return best test_all_forms() 

Add to loop three more advanced positivity functions to test — each with a different physical motivation. Add these to your loop: 1. Logarithmic decay — motivated by renormalization flow: pos = alpha / (np.log(x + 1.1) + 1) 2. Oscillatory damping — echoes zeta’s own oscillations: pos = alpha np.exp(-0.3 x) np.cos(0.8 x) 3. Fractional power — inspired by dimensional scaling: pos = alpha / (x 0.7 + 1) After running the sweep, check which one gives the lowest mean error against the real zeta zeros. The winner tells you which mathematical behavior the positivity wall actually follows in your 59D operator.
